
[package]
name="learn-rust-fundamental"
version="0.0.1"
edition="2021"

[[bin]]
name="data-type"
path="data-type/src/main/main_exe.rs"

[[bin]]
name="conditional-statement"
path="conditional-statement/src/main/main_exe.rs"

[[bin]]
name="smart-pointer"
path="smart-pointer/src/main/main_exe.rs"